### ISSUE TITLE
这个插件只能用在DOCKER里吗

### ISSUE THREAD

**Issue by mxli441** [actiontech/sqle-pg-plugin#2]
我在普通CENTOS里安装时遇到如下问题，是否只能装在DOCKER环境里？
# make docker_install
which: no docker in (/usr/local/apache-zookeeper-3.6.0-bin/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/local/jdk1.8.0_131/bin:/root/bin)
run -v /opt/sqle/plugins/sqle-pg-plugin-main:/universe --rm golang:1.14 sh -c "cd /universe && make install "
/bin/sh: run: command not found
make: *** [docker_install] Error 127

**Comment by drivebyer** [comment]
有 Go 语言编译环境的话，可以直接编译。如果只是试用的话，可以用我们编译好的二进制，https://github.com/actiontech/sqle/releases/download/v1.2111.0-pre1/sqle-pg-plugin 。

**Comment by mxli441** [comment]
好的，谢了
