### ISSUE TITLE
PG的审核规则模版只有一条，且不能通过手动添加新规则

### ISSUE THREAD

**Issue by mxli441** [actiontech/sqle-pg-plugin#3]
PG的审核规则模版只有一条，且不能通过手动添加新规则，是否是因为我使用了试用版的原因，还是说这一块要等后期代码更新？

**Comment by sjjian** [comment]
@mxli441 
1. PG插件目前只提供了一条样例，你可以自己开发实现其他规则，我们下周会优化插件的开发库，添加规则将会很方便，内容将会同步到这个文档 [数据库插件开发文档](https://actiontech.github.io/sqle-docs-cn/3.modules/3.7_auditplugin/auditplugin_development.html)。
2. 或者也可以提供一些规则给我们，我们后期有空的话会实现。

以上，可以随时关注我们的发版信息

**Comment by mxli441** [comment]
好的
